# Generated by Django 5.2.6 on 2025-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('occupied_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Vacant', max_length=20)),
            ],
        ),
    ]
