# Generated by Django 5.2.5 on 2025-09-20 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='outpass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outpass',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outpass',
            name='parent_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outpass',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
