# Generated by Django 5.2.5 on 2025-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0002_outpass_approved_at_outpass_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpass',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='outpass',
            name='parent_consent',
        ),
        migrations.RemoveField(
            model_name='outpass',
            name='rejected_at',
        ),
        migrations.AlterField(
            model_name='outpass',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
    ]
